package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

type Keymap struct {
	Mode string
	Key  string
	Desc string
	Loc  string // e.g. lua/config/keymaps.lua
}

var (
	// vim.keymap.set("n", "<leader>x", ..., { desc = "..." })
	reSet = regexp.MustCompile(`vim\.keymap\.set\(\s*"([^"]+)"\s*,\s*"([^"]+)"[^}]+desc\s*=\s*"([^"]+)"`)
	// same but single quotes
	reSetSq = regexp.MustCompile(`vim\.keymap\.set\(\s*'([^']+)'\s*,\s*'([^']+)'[^}]+desc\s*=\s*"([^"]+)"`)
	// also handle 'desc' single-quoted? rare; fallback
)

func main() {
	root := filepath.Join("..", "..") // scripts/gen-keybinds -> nvim root
	// if run from scripts/gen-keybinds, root is ../..
	absRoot, _ := filepath.Abs(".")
	if strings.HasSuffix(absRoot, "scripts/gen-keybinds") {
		absRoot = filepath.Dir(filepath.Dir(absRoot))
		root = absRoot
	} else {
		root = absRoot
	}

	outPath := filepath.Join(root, "KEYBINDS.md")
	var all []Keymap

	// 1) config/keymaps.lua
	if km := extractFromFile(filepath.Join(root, "lua/config/keymaps.lua"), "lua/config/keymaps.lua"); len(km) > 0 {
		all = append(all, km...)
	}

	// 2) utils/lsp.lua
	if km := extractFromFile(filepath.Join(root, "lua/utils/lsp.lua"), "lua/utils/lsp.lua"); len(km) > 0 {
		all = append(all, km...)
	}

	// 3) plugins/**/*.lua
	_ = filepath.WalkDir(filepath.Join(root, "lua/plugins"), func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".lua") {
			return nil
		}
		rel, _ := filepath.Rel(root, path)
		km := extractFromFile(path, rel)
		all = append(all, km...)
		return nil
	})

	buf := new(bytes.Buffer)
	fmt.Fprintln(buf, "# Neovim Keybindings")
	fmt.Fprintln(buf, "")
	fmt.Fprintln(buf, "> Auto-generated by `scripts/gen-keybinds/main.go`. Do not edit manually; edit source files and regenerate.")
	fmt.Fprintln(buf, "> Run: `cd nvim/.config/nvim && go run ./scripts/gen-keybinds`")
	fmt.Fprintln(buf, "")

	// Group: Core
	core := filterByLoc(all, "lua/config/keymaps.lua")
	if len(core) > 0 {
		fmt.Fprintln(buf, "## Core (lua/config/keymaps.lua)")
		fmt.Fprintln(buf, "")
		writeTable(buf, core)
	}

	// Group: LSP
	lsp := filterByLoc(all, "lua/utils/lsp.lua")
	if len(lsp) > 0 {
		fmt.Fprintln(buf, "## LSP (lua/utils/lsp.lua)")
		fmt.Fprintln(buf, "")
		writeTable(buf, lsp)
	}

	// Group: Plugins
	plugins := filterNotIn(all, []string{"lua/config/keymaps.lua", "lua/utils/lsp.lua"})
	if len(plugins) > 0 {
		// group by file
		byFile := map[string][]Keymap{}
		for _, k := range plugins {
			byFile[k.Loc] = append(byFile[k.Loc], k)
		}
		files := make([]string, 0, len(byFile))
		for f := range byFile {
			files = append(files, f)
		}
		sort.Strings(files)
		fmt.Fprintln(buf, "## Plugins")
		fmt.Fprintln(buf, "")
		for _, f := range files {
			fmt.Fprintf(buf, "### %s\n\n", filepath.Base(f))
			writeTable(buf, byFile[f])
		}
	}

	if err := os.WriteFile(outPath, buf.Bytes(), 0644); err != nil {
		panic(err)
	}
	fmt.Println("wrote", outPath)
}

func extractFromFile(path, rel string) []Keymap {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var res []Keymap
	scanner := bufio.NewScanner(bytes.NewReader(b))
	// increase buffer for long lines
	const maxTokenSize = 1024 * 1024
	scanner.Buffer(make([]byte, maxTokenSize), maxTokenSize)
	scanner.Split(bufio.ScanLines)

	for scanner.Scan() {
		line := scanner.Text()
		// skip comments roughly
		if idx := strings.Index(line, "--"); idx >= 0 {
			// simple: if before paren? not critical
		}
		m := reSet.FindStringSubmatch(line)
		if len(m) == 4 {
			res = append(res, Keymap{Mode: m[1], Key: m[2], Desc: m[3], Loc: rel})
			continue
		}
		m = reSetSq.FindStringSubmatch(line)
		if len(m) == 4 {
			res = append(res, Keymap{Mode: m[1], Key: m[2], Desc: m[3], Loc: rel})
			continue
		}
	}
	return res
}

func filterByLoc(in []Keymap, loc string) []Keymap {
	var out []Keymap
	for _, k := range in {
		if k.Loc == loc {
			out = append(out, k)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Key < out[j].Key })
	return out
}

func filterNotIn(in []Keymap, locs []string) []Keymap {
	set := map[string]bool{}
	for _, l := range locs {
		set[l] = true
	}
	var out []Keymap
	for _, k := range in {
		if !set[k.Loc] {
			out = append(out, k)
		}
	}
	return out
}

func writeTable(buf *bytes.Buffer, km []Keymap) {
	fmt.Fprintln(buf, "| Key | Mode | Description |")
	fmt.Fprintln(buf, "|---|------|-------------|")
	for _, k := range km {
		// escape pipes in desc? rare
		desc := strings.ReplaceAll(k.Desc, "|", "\\|")
		fmt.Fprintf(buf, "| `%s` | `%s` | %s |\n", k.Key, k.Mode, desc)
	}
	fmt.Fprintln(buf, "")
}
