# === Nightfox Theme for tmux ===
# Inspired by EdenEast/nightfox.nvim

# Общие цвета
set -g status-style bg='#131a24',fg='#cdcecf'
set -g message-style bg='#19232c',fg='#cdcecf'
set -g pane-border-style fg='#2e3b45'
set -g pane-active-border-style fg='#50a0b0'
set -g mode-style bg='#50a0b0',fg='#131a24'

# Status left
set -g status-left-length 60
set -g status-left "#[fg=#50a0b0,bg=#131a24]#[fg=#131a24,bg=#50a0b0,bold] #S  #[fg=#50a0b0,bg=#131a24]"

# Status right
set -g status-right-length 120
set -g status-right "#[fg=#cdcecf,bg=#131a24]󰥔 %H:%M #[fg=#c0b18b,bg=#131a24] 󰃭 %d-%m-%Y#[fg=#50a0b0,bg=#131a24]  #(whoami)@#H "
set -g window-status-format "#[fg=#6f7e8c] 󰈚 #I:#W "
set -g window-status-current-format "#[fg=#d3e3e8,bg=#1e2a32,bold] 󰈚 #I:#W "
set -g window-status-activity-style fg='#50a0b0',bg='#131a24'
set -g window-status-separator ""


